-- Insert Test Data for Global Search
-- Date: 2026-02-02
-- Purpose: Insert test contacts, properties, and deals to make search functional
-- Embeddings will be auto-generated by triggers

-- Insert test contacts
INSERT INTO contacts (tenant_id, first_name, last_name, email, phone, company, contact_type, notes)
VALUES
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'Sarah', 'Johnson', 'sarah.johnson@example.com', '(555) 123-4567', 'Johnson Realty Group', 'agent', 'Top producer in commercial real estate. Specializes in office buildings and retail spaces. Lead Broker with 15 years experience.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'Michael', 'Chen', 'michael.chen@example.com', '(555) 234-5678', 'Century Properties', 'agent', 'Residential specialist focusing on luxury homes and waterfront properties. Senior Agent with proven track record.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'Jennifer', 'Martinez', 'jennifer.martinez@example.com', '(555) 345-6789', 'Elite Homes Realty', 'buyer', 'First-time homebuyer looking for condos in downtown Seattle. Budget 800K-1M. Excellent communication and responsive.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'David', 'Thompson', 'david.thompson@example.com', '(555) 456-7890', 'Thompson Investment Group', 'buyer', 'Investment property expert looking for multi-family properties. Cash buyer. Handles commercial portfolios.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'Emily', 'Rodriguez', 'emily.rodriguez@example.com', '(555) 567-8901', 'Coastal Properties LLC', 'seller', 'Selling vacation home on the coast. Motivated seller. Property is waterfront with private beach access.')
ON CONFLICT DO NOTHING;

-- Insert test properties
INSERT INTO properties (tenant_id, address, city, state, zip_code, property_type, status, price, square_feet, description)
VALUES
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', '123 Main Street', 'Seattle', 'WA', '98101', 'commercial', 'active', 2500000, 15000, 'Prime downtown office building with modern amenities. Recently renovated with energy-efficient systems. Perfect for corporate headquarters or multi-tenant office space.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', '456 Lake View Drive', 'Bellevue', 'WA', '98004', 'single_family', 'active', 3750000, 4500, 'Stunning waterfront estate with panoramic lake views. Custom-built luxury home featuring gourmet kitchen, home theater, and private dock. Gated community.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', '789 Pike Street Suite 2501', 'Seattle', 'WA', '98101', 'condo', 'active', 875000, 1200, 'High-rise luxury condo in the heart of downtown Seattle. Floor-to-ceiling windows, modern finishes, and resort-style amenities. Walk to everything.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', '321 Broadway Avenue', 'Tacoma', 'WA', '98402', 'multi_family', 'active', 1250000, 8000, 'Fully occupied 6-unit apartment building. Strong rental history with stable tenants. Recently updated plumbing and electrical. Great cash flow opportunity.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', '555 Commercial Boulevard', 'Redmond', 'WA', '98052', 'commercial', 'active', 450000, 3500, 'Prime retail space in high-traffic shopping center. Excellent visibility and parking. Perfect for restaurant, boutique, or service business.')
ON CONFLICT DO NOTHING;

-- Insert test deals (using actual schema: deal_type, stage, estimated_value, notes)
INSERT INTO deals (tenant_id, deal_type, stage, estimated_value, expected_close_date, notes)
VALUES
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'buyer', 'offer', 2500000, CURRENT_DATE + INTERVAL '30 days', 'Downtown Office Building - Johnson Purchase. Sarah Johnson interested in purchasing 123 Main Street office building for corporate headquarters.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'buyer', 'showing', 3750000, CURRENT_DATE + INTERVAL '45 days', 'Lake View Waterfront - Chen Family. Michael Chen representing buyers interested in luxury waterfront estate.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'buyer', 'contacted', 875000, CURRENT_DATE + INTERVAL '60 days', 'Downtown Condo - Martinez First-Timer. Jennifer Martinez first-time homebuyer interested in downtown condo.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'buyer', 'under_contract', 1250000, CURRENT_DATE + INTERVAL '20 days', 'Multi-Family Investment - Thompson Portfolio. David Thompson cash buyer conducting due diligence.'),
  ('5098bedb-a0bc-40ae-83fa-799df8f44981', 'seller', 'lead', 1500000, CURRENT_DATE + INTERVAL '90 days', 'Coastal Vacation Property - Rodriguez. Emily Rodriguez selling waterfront vacation home with private beach access.')
ON CONFLICT DO NOTHING;
